name: 'ctfPlugin'
version: '1.0.0'
main: 'com.jonathancbate.mc.ctf.CaptureTheFlag'
api-version: '1.21.5'
commands:
  start:
    description: Start the timer for Capture the Flag
    usage: /start
    permission: ctf.admin